# add stages here 
stages:
  stage_name:
    cmd: python src/stage_01_prepare.py
    deps:
    - src/stage_01_prepare.py
    - data/data.xml
    - src/utils/common.py
    - src/utils/data_mgmt.py
    - configs/config.yaml

    params:
      - prepare.random_seed
      - prepare.split_ratio
    outs:
    - artifacts/processed_data/train.tsv
    - artifacts/processed_data/test.tsv

