# add stages here 
stages:
  Preparation:
    cmd: python src/stage_01_prepare.py
    deps:
    - src/stage_01_prepare.py
    - data/data.xml
    - src/utils/common.py
    - src/utils/data_mgmt.py
    - configs/config.yaml

    params:
      - prepare.random_seed
      - prepare.split_ratio
    outs:
    - artifacts/processed_data/train.tsv
    - artifacts/processed_data/test.tsv


  feature_extraction:
    cmd: python src/stage_02_feature_engineering.py
    deps:
    - src/stage_02_feature_engineering.py
    - artifacts/processed_data/train.tsv
    - artifacts/processed_data/test.tsv
    - src/utils/common.py
    - src/utils/featurize.py
    - configs/config.yaml

    params:
      - FEATURES.MAX_FEATURES
      - FEATURES.NGRAMS
    outs:
    - artifacts/features/features_train.pkl
    - artifacts/features/features_test.pkl


  model_training:
    cmd: python src/stage_03_train.py --config=configs/config.yaml --params=params.yaml 
    deps:
    - src/stage_03_train.py
    - artifacts/features/features_train.pkl
    - src/utils/common.py
    - configs/config.yaml

    params:
      - TRAIN.SEED
      - TRAIN.N_ESTIMATORS
      - TRAIN.MAX_DEPTH
      - TRAIN.MIN_SAMPLES_SPLIT
    outs:
    - artifacts/model/model.pkl


  model_evaluation:
    cmd: python src/stage_04_evaluate.py --config=configs/config.yaml
    
    deps:
      - src/stage_04_evaluate.py
      - artifacts/features/features_test.pkl
      - artifacts/model/model.pkl
      - src/utils/common.py
      - configs/config.yaml

    metrics:
      - metrics.json:
          cache: false

    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: fpr
          y: tpr

  run_plots_command:
    cmd: dvc plots diff


