# This contains params to be used by the stages to train or predict
prepare:
  split_ratio: 0.3
  random_seed: 42

FEATURES:
  MAX_FEATURES: 5000
  NGRAMS: 2

TRAIN:
  SEED: 42
  N_ESTIMATORS: 90
  MAX_DEPTH: 8
  MIN_SAMPLES_SPLIT: 15
  OOB_SCORE: True