# This contains params to be used by the stages to train or predict
prepare:
  split_ratio: 0.3
  random_seed: 42

FEATURES:
  MAX_FEATURES: 6000
  NGRAMS: 2

TRAIN:
  SEED: 42
  N_ESTIMATORS: 120
  MAX_DEPTH: 10
  MIN_SAMPLES_SPLIT: 20
  OOB_SCORE: true
