# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PROCESSED_DATA: processed_data
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURES:
    FEATURE_DIR: features
    FEATURE_TRAIN_DATA: features_train.pkl
    FEATURE_TEST_DATA: features_test.pkl
  MODEL:
    MODEL_DIR: model
    MODEL_FILE: model.pkl

METRICS:
  METRICS_DIR: metrics
  METRICS_FILE: metrics.json

PLOTS:
  PLOTS_DIR: plots
  PRC: prc.png
  PRC_FILE: prc.json
  ROC: roc.png
  ROC_FILE: roc.json
  AVG_PRECISION_FILE: avg_precision.json
  ROC_AUC_SCORE_FILE: roc_auc_score.json
  
source_data:
  source_data_dir: data
  source_data_file: data.xml
